version: "3.9"
services:
  golang_int_comms:
    build:
      context: .
      network: host
    restart: on-failure
    network_mode: host
    privileged: true
    volumes: 
      - .:/var/www/comms-int
      - ./sockets:/tmp/www/comms/
    command: "go run main.go"
    tty: true
  python_controller:
    build:
      context: ./supporting_scripts
    network_mode: host
    privileged: true
    volumes: 
      - ./supporting_scripts:/var/www/comms-int
      - ./sockets:/tmp/www/comms/