version: "3.9"
services:
  golang_int_comms:
    build:
      context: .
      network: host
    restart: on-failure
    network_mode: host
    privileged: true
    volumes: 
      - ./sockets:/tmp/www/comms/
